updating licensing text
IBM/crypto-discovery-news-sentiment-analysis pull request #11
Opened 2018-11-29 02:41 UTC by ljbennett62

2018-11-29 10:12 UTC, dolph requested changes
Same issue as similar patches.

2018-11-29 16:04 UTC, ljbennett62 commented
@dolph - amended - please review

2018-11-30 05:12 UTC, markstur approved these changes

2018-12-19 21:41 UTC, dolph approved these changes

2018-12-19 21:42 UTC, merged